# Generated by Django 4.0.5 on 2022-06-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_img', models.CharField(max_length=2000)),
                ('icon_description', models.CharField(max_length=200)),
                ('time_todo', models.CharField(max_length=200)),
            ],
        ),
    ]
